(1, 'Shayna Chaman', '202-865-8027', 'schaman0@hexun.com', '4871 Holy Cross Way', 'Washington', 'District of Columbia');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (2, 'Regine Reimers', '913-989-6845', 'rreimers1@microsoft.com', '538 Thierer Court', 'Shawnee Mission', 'Kansas');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (3, 'Ced Brasher', '619-118-8476', null, '146 La Follette Crossing', 'San Diego', 'California');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (4, 'Pearle Todarini', '573-558-4246', 'ptodarini3@huffingtonpost.com', '7 Troy Road', 'Columbia', 'Missouri');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (5, 'Brion Ridewood', '502-259-3691', null, '7327 Hanover Parkway', 'Louisville', 'Kentucky');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (6, 'Culver Haythorne', '704-470-6377', 'chaythorne5@tamu.edu', '2 Susan Court', 'Winston Salem', 'North Carolina');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (7, 'Caroljean Goulden', '812-161-5317', 'cgoulden6@google.it', '79442 Melody Crossing', 'Evansville', 'Indiana');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (8, 'Kelvin Harbottle', '316-324-5700', 'kharbottle7@blogtalkradio.com', '05913 Graedel Court', 'Wichita', 'Kansas');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (9, 'Andras Basso', '908-871-4028', 'abasso8@sciencedirect.com', '006 Ruskin Hill', 'Elizabeth', 'New Jersey');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (10, 'Oren Harris', '830-283-0326', null, '0 Sachtjen Lane', 'San Antonio', 'Texas');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (11, 'Valaree Purchon', '203-397-4036', 'vpurchona@bing.com', '59946 Kensington Alley', 'Waterbury', 'Connecticut');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (12, 'Crosby Barday', '915-510-8204', 'cbardayb@sphinn.com', '7345 Westerfield Parkway', 'El Paso', 'Texas');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (13, 'Collin People', '570-981-0158', 'cpeoplec@reference.com', '59273 Pepper Wood Circle', 'Scranton', 'Pennsylvania');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (14, 'Brenna Coners', '209-157-5847', 'bconersd@zimbio.com', '4 Commercial Drive', 'Stockton', 'California');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (15, 'Shoshanna Stonhewer', '309-219-8907', 'sstonhewere@gnu.org', '41 Mayer Trail', 'Carol Stream', 'Illinois');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (16, 'Bearnard Fairholme', '704-645-4565', 'bfairholmef@live.com', '47711 Linden Road', 'Charlotte', 'North Carolina');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (17, 'Robin Andreev', '206-379-5077', 'randreevg@ezinearticles.com', '06 Brentwood Center', 'Seattle', 'Washington');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (18, 'Bartlett Lewerenz', '954-702-2999', null, '0004 Shoshone Center', 'Fort Lauderdale', 'Florida');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (19, 'Glori Warlowe', '612-876-6940', null, '9335 Commercial Lane', 'Minneapolis', 'Minnesota');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (20, 'Aldon Cristou', '626-457-9435', 'acristouj@addtoany.com', '9 Maywood Plaza', 'Van Nuys', 'California');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (21, 'Abbe Sidnell', '315-990-5621', 'asidnellk@virginia.edu', '9068 Esker Parkway', 'Utica', 'New York');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (22, 'Mary Korbmaker', '570-407-9549', 'mkorbmakerl@latimes.com', '57069 Northwestern Street', 'Scranton', 'Pennsylvania');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (23, 'Tully Blindmann', '615-938-5689', 'tblindmannm@1688.com', '25 Dayton Park', 'Nashville', 'Tennessee');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (24, 'Karlan Walby', '970-122-4060', 'kwalbyn@netvibes.com', '01 Village Court', 'Grand Junction', 'Colorado');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (25, 'Charline Triner', '570-808-6002', 'ctrinero@businessinsider.com', '3922 Old Gate Point', 'Wilkes Barre', 'Pennsylvania');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (26, 'Berky Caldairou', '510-115-2207', 'bcaldairoup@360.cn', '2 Killdeer Point', 'Oakland', 'California');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (27, 'Madlin Facey', '717-119-5074', 'mfaceyq@va.gov', '23936 Hagan Parkway', 'Harrisburg', 'Pennsylvania');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (28, 'Sarina Devaney', '253-772-1412', 'sdevaneyr@go.com', '6 Knutson Crossing', 'Tacoma', 'Washington');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (29, 'Gregg Storrie', '601-834-5654', 'gstorries@a8.net', '4 Sloan Drive', 'Hattiesburg', 'Mississippi');
insert into Customers (CustomerId, Name, Phone, Email, Address, City, State) values (30, 'Sapphira Smalles', '702-646-4593', null, '5161 Buena Vista Place', 'Las Vegas', 'Nevada');
